local spGetUnitPosition = Spring.GetUnitPosition
local spGetGroundHeight = Spring.GetGroundHeight
local spGiveOrderToUnit = Spring.GiveOrderToUnit
local spGetUnitRulesParam = Spring.GetUnitRulesParam
local spGetSelectedUnitsSorted = Spring.GetSelectedUnitsSorted
local spGetUnitRulesParam = Spring.GetUnitRulesParam
local spGetUnitVelocity = Spring.GetUnitVelocity
-- local spGetUnitHeading = Spring.GetUnitHeading
-- local spValidUnitID = Spring.ValidUnitID
-- local spGetUnitIsDead = Spring.GetUnitIsDead
-- local spGetUnitWeaponState = Spring.GetUnitWeaponState
-- local spGetUnitIsStunned = Spring.GetUnitIsStunned
